### ISSUE TITLE
Half-Init

### ISSUE THREAD

**Issue by thiagodefreitas** [ros-industrial/ros_canopen#27]
Error description:
- After init, only a part of the modules can be moved, although the service returns OK

Occurance(s) (when? Which hardware? How often?):
- sometimes
- Schunk LWA4D, cob4-2 arms

How to reproduce the error:
- bringup
- init
- move

**Comment by floweisshardt** [comment]
@thiagodefreitas: can you record a candump for that and send it to @ipa-mdl ?

**Comment by thiagodefreitas** [comment]
https://gist.github.com/thiagodefreitas/07e035ffe0537196ed31

**Comment by thiagodefreitas** [comment]
@ipa-mdl The hardware mode seems to change during _init_, everytime a new controller is loaded from the ROS side. I could see a transition to velocity mode and to PP mode, and then back to IP mode.

**Comment by floweisshardt** [comment]
switching controller is fixed now in cob_control_mode_adapter

**Comment by floweisshardt** [comment]
another candump for half init: https://gist.github.com/ipa-fmw/43f7fe0e3abc5fcf96a0
was recorded on cob4-2 right_arm. Only the first arm module could be moved afterwards. restarting bringup and init again didn't help. also recover was without effect.

**Comment by floweisshardt** [comment]
this is still not fixed and occurred in Berlin again. 
@ipa-mdl and @thiagodefreitas: any ideas how and where  to fix this?

**Comment by thiagodefreitas** [comment]
@ipa-mdl Could this be related to https://github.com/ipa320/ros_canopen/pull/63?

**Comment by mathias-luedtke** [comment]
This issue is still present with my fork, but the other fixes (9e97a19a372a3335e8ac8e7c445aa87abcd6f307 and a7b4556423022a38032af809f8b1d6c10ae56920) may help.

**Comment by floweisshardt** [comment]
@thiagodefreitas: another candump from today con cob4-2 arm left: https://gist.github.com/ipa-fmw/0f019d71ea1a940397ee

**Comment by floweisshardt** [comment]
solved in #82
